### ISSUE TITLE
Auto-save options

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/github-notifier-chrome#38]
A "Save" button is so 2000. We can instead just auto-save when the user changes the settings by listening to the `change` event on the form inputs. This way we can also remove the alert message thingy.

**Comment by sindresorhus** [comment]
@Narno Interested? :)

**Comment by Narno** [comment]
Feature commited in branch "feature-38-auto-save-options": d36885c7ea57aa782cbb0c6598d00770960791bd

**Comment by sindresorhus** [comment]
@Narno Can you submit a pull request from it? Easier to review that way.
