### ISSUE TITLE
Usability improvement

### ISSUE THREAD

**Issue by kaplun** [sindresorhus/github-notifier-chrome#41]
When *Only show unread count for issues I'm participating in* functionality is enabled, it would be great if, when clicking on this extension icon in Chrome, in case there is at least *one issue I'm participating in*, to be presented directly with the *Participating* tab of GitHub.

**Comment by sindresorhus** [comment]
Fixed in https://github.com/sindresorhus/github-notifier-chrome/commit/ae71376ae333d8767e2d7947c3e7c8dc787f09f6.
