### ISSUE TITLE
custom url for firefox-plugin

### ISSUE THREAD

**Issue by deguss** [sindresorhus/github-notifier-chrome#47]
hi @sindresorhus 

I just wanted to aks if you have time to update the firefox plugin with all the nice features the chrom plugin has. At least the custor url would be nice for me.
Thank you. Daniel

**Comment by sindresorhus** [comment]
Not really. I haven't used Firefox in years. Open issues on the Firefox plugin issue tracker for what's missing and someone might be interested in helping out doing it ;)

**Comment by deguss** [comment]
thank you
